// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accommodation_detail.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const checkAccommodationDetailExists = `-- name: CheckAccommodationDetailExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            ` + "`" + `ecommerce_go_accommodation_detail` + "`" + `
        WHERE
            ` + "`" + `id` + "`" + ` = ?
    )
`

func (q *Queries) CheckAccommodationDetailExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAccommodationDetailExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccommodationDetail = `-- name: CreateAccommodationDetail :exec
INSERT INTO
    ` + "`" + `ecommerce_go_accommodation_detail` + "`" + ` (
        ` + "`" + `id` + "`" + `,
        ` + "`" + `accommodation_id` + "`" + `,
        ` + "`" + `name` + "`" + `,
        ` + "`" + `guests` + "`" + `,
        ` + "`" + `beds` + "`" + `,
        ` + "`" + `facilities` + "`" + `,
        ` + "`" + `available_rooms` + "`" + `,
        ` + "`" + `price` + "`" + `,
        ` + "`" + `created_at` + "`" + `,
        ` + "`" + `updated_at` + "`" + `
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAccommodationDetailParams struct {
	ID              string
	AccommodationID string
	Name            string
	Guests          uint8
	Beds            json.RawMessage
	Facilities      json.RawMessage
	AvailableRooms  uint8
	Price           string
	CreatedAt       uint64
	UpdatedAt       uint64
}

func (q *Queries) CreateAccommodationDetail(ctx context.Context, arg CreateAccommodationDetailParams) error {
	_, err := q.db.ExecContext(ctx, createAccommodationDetail,
		arg.ID,
		arg.AccommodationID,
		arg.Name,
		arg.Guests,
		arg.Beds,
		arg.Facilities,
		arg.AvailableRooms,
		arg.Price,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAccommodationDetails = `-- name: DeleteAccommodationDetails :exec
UPDATE ` + "`" + `ecommerce_go_accommodation_detail` + "`" + `
SET
    ` + "`" + `is_deleted` + "`" + ` = 1
WHERE
    ` + "`" + `id` + "`" + ` = ?
`

func (q *Queries) DeleteAccommodationDetails(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccommodationDetails, id)
	return err
}

const getAccommodationDetail = `-- name: GetAccommodationDetail :one
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `accommodation_id` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `guests` + "`" + `,
    ` + "`" + `beds` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `available_rooms` + "`" + `,
    ` + "`" + `price` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `updated_at` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation_detail` + "`" + `
WHERE
    ` + "`" + `id` + "`" + ` = ?
    and ` + "`" + `accommodation_id` + "`" + ` = ? and ` + "`" + `is_deleted` + "`" + `= 0
`

type GetAccommodationDetailParams struct {
	ID              string
	AccommodationID string
}

type GetAccommodationDetailRow struct {
	ID              string
	AccommodationID string
	Name            string
	Guests          uint8
	Beds            json.RawMessage
	Facilities      json.RawMessage
	AvailableRooms  uint8
	Price           string
	CreatedAt       uint64
	UpdatedAt       uint64
}

func (q *Queries) GetAccommodationDetail(ctx context.Context, arg GetAccommodationDetailParams) (GetAccommodationDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getAccommodationDetail, arg.ID, arg.AccommodationID)
	var i GetAccommodationDetailRow
	err := row.Scan(
		&i.ID,
		&i.AccommodationID,
		&i.Name,
		&i.Guests,
		&i.Beds,
		&i.Facilities,
		&i.AvailableRooms,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccommodationDetails = `-- name: GetAccommodationDetails :many
SELECT
    ` + "`" + `id` + "`" + `,
    ` + "`" + `accommodation_id` + "`" + `,
    ` + "`" + `name` + "`" + `,
    ` + "`" + `guests` + "`" + `,
    ` + "`" + `beds` + "`" + `,
    ` + "`" + `discount_id` + "`" + `,
    ` + "`" + `facilities` + "`" + `,
    ` + "`" + `available_rooms` + "`" + `,
    ` + "`" + `price` + "`" + `,
    ` + "`" + `created_at` + "`" + `,
    ` + "`" + `updated_at` + "`" + `
FROM
    ` + "`" + `ecommerce_go_accommodation_detail` + "`" + `
WHERE
    ` + "`" + `accommodation_id` + "`" + ` = ? and ` + "`" + `is_deleted` + "`" + `= 0
`

type GetAccommodationDetailsRow struct {
	ID              string
	AccommodationID string
	Name            string
	Guests          uint8
	Beds            json.RawMessage
	DiscountID      sql.NullString
	Facilities      json.RawMessage
	AvailableRooms  uint8
	Price           string
	CreatedAt       uint64
	UpdatedAt       uint64
}

func (q *Queries) GetAccommodationDetails(ctx context.Context, accommodationID string) ([]GetAccommodationDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAccommodationDetails, accommodationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccommodationDetailsRow
	for rows.Next() {
		var i GetAccommodationDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccommodationID,
			&i.Name,
			&i.Guests,
			&i.Beds,
			&i.DiscountID,
			&i.Facilities,
			&i.AvailableRooms,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccommodationDetail = `-- name: UpdateAccommodationDetail :exec
UPDATE ` + "`" + `ecommerce_go_accommodation_detail` + "`" + `
SET
    ` + "`" + `name` + "`" + ` = ?,
    ` + "`" + `guests` + "`" + ` = ?,
    ` + "`" + `beds` + "`" + ` = ?,
    ` + "`" + `facilities` + "`" + ` = ?,
    ` + "`" + `available_rooms` + "`" + ` = ?,
    ` + "`" + `price` + "`" + ` = ?,
    ` + "`" + `updated_at` + "`" + ` = ?
WHERE
    ` + "`" + `id` + "`" + ` = ?
    and ` + "`" + `accommodation_id` + "`" + ` = ? and ` + "`" + `is_deleted` + "`" + `= 0
`

type UpdateAccommodationDetailParams struct {
	Name            string
	Guests          uint8
	Beds            json.RawMessage
	Facilities      json.RawMessage
	AvailableRooms  uint8
	Price           string
	UpdatedAt       uint64
	ID              string
	AccommodationID string
}

func (q *Queries) UpdateAccommodationDetail(ctx context.Context, arg UpdateAccommodationDetailParams) error {
	_, err := q.db.ExecContext(ctx, updateAccommodationDetail,
		arg.Name,
		arg.Guests,
		arg.Beds,
		arg.Facilities,
		arg.AvailableRooms,
		arg.Price,
		arg.UpdatedAt,
		arg.ID,
		arg.AccommodationID,
	)
	return err
}
